name: github pages hugo

on:
  push:
    branches:
      - source-1

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Set up Deploy Key
      run: echo "${{ secrets.id_ed25519 }}" > ~/.ssh/id_ed25519
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.id_ed25519 }}

    - name: Set permissions for SSH directory and key
      run: chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_ed25519

    - name: check key
      run: cat ~/.ssh/id_ed25519

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: master
